2024-11-21 15:15:30,613 - MainThread - sqlmesh.core.config.scheduler - WARNING - The snowflake engine is not recommended for storing SQLMesh state in production deployments. Please see https://sqlmesh.readthedocs.io/en/stable/guides/configuration/#state-connection for a list of recommended engines and more information. (scheduler.py:94)
2024-11-21 15:15:30,615 - MainThread - snowflake.connector.connection - INFO - Snowflake Connector for Python Version: 3.12.3, Python Version: 3.12.3, Platform: Linux-6.8.0-48-generic-x86_64-with-glibc2.39 (connection.py:414)
2024-11-21 15:15:30,615 - MainThread - snowflake.connector.connection - INFO - Connecting to GLOBAL Snowflake domain (connection.py:1197)
2024-11-21 15:15:30,615 - MainThread - snowflake.connector.connection - INFO - This connection is in OCSP Fail Open Mode. TLS Certificates would be checked for validity and revocation status. Any other Certificate Revocation related exceptions or OCSP Responder failures would be disregarded in favor of connectivity. (connection.py:1278)
2024-11-21 15:15:31,194 - MainThread - snowflake.connector.cursor - INFO - Number of results in first chunk: 3 (cursor.py:1166)
2024-11-21 15:15:31,302 - MainThread - snowflake.connector.cursor - INFO - Number of results in first chunk: 1 (cursor.py:1166)
2024-11-21 15:15:31,419 - MainThread - snowflake.connector.cursor - INFO - Number of results in first chunk: 1 (cursor.py:1166)
2024-11-21 15:15:31,525 - MainThread - snowflake.connector.cursor - INFO - Number of results in first chunk: 1 (cursor.py:1166)
2024-11-21 15:15:31,658 - MainThread - snowflake.connector.cursor - INFO - Number of results in first chunk: 3 (cursor.py:1166)
2024-11-21 15:15:31,772 - MainThread - snowflake.connector.cursor - INFO - Number of results in first chunk: 1 (cursor.py:1166)
2024-11-21 15:15:31,884 - MainThread - snowflake.connector.cursor - INFO - Number of results in first chunk: 1 (cursor.py:1166)
2024-11-21 15:15:31,994 - MainThread - snowflake.connector.cursor - INFO - Number of results in first chunk: 1 (cursor.py:1166)
2024-11-21 15:15:32,291 - MainThread - snowflake.connector.cursor - INFO - Number of results in first chunk: 11 (cursor.py:1166)
2024-11-21 15:15:32,401 - MainThread - snowflake.connector.cursor - INFO - Number of results in first chunk: 1 (cursor.py:1166)
2024-11-21 15:15:32,528 - MainThread - snowflake.connector.cursor - INFO - Number of results in first chunk: 10 (cursor.py:1166)
2024-11-21 15:15:32,642 - MainThread - snowflake.connector.cursor - INFO - Number of results in first chunk: 1 (cursor.py:1166)
2024-11-21 15:15:32,688 - MainThread - sqlmesh.core.snapshot.evaluator - INFO - Auditing snapshot SnapshotId<"SQLMESH_DEMO"."SQL_MODELS"."VIEW_MODEL": 1325925580> (evaluator.py:428)
2024-11-21 15:15:32,689 - MainThread - snowflake.connector.connection - INFO - Snowflake Connector for Python Version: 3.12.3, Python Version: 3.12.3, Platform: Linux-6.8.0-48-generic-x86_64-with-glibc2.39 (connection.py:414)
2024-11-21 15:15:32,690 - MainThread - snowflake.connector.connection - INFO - Connecting to GLOBAL Snowflake domain (connection.py:1197)
2024-11-21 15:15:32,690 - MainThread - snowflake.connector.connection - INFO - This connection is in OCSP Fail Open Mode. TLS Certificates would be checked for validity and revocation status. Any other Certificate Revocation related exceptions or OCSP Responder failures would be disregarded in favor of connectivity. (connection.py:1278)
2024-11-21 15:15:33,167 - MainThread - sqlmesh.core.engine_adapter.base - INFO - Executing SQL: DESCRIBE TABLE "SQLMESH_DEMO"."sqlmesh__SQL_MODELS"."SQL_MODELS__VIEW_MODEL__704933569" (base.py:2062)
2024-11-21 15:15:33,285 - MainThread - snowflake.connector.cursor - INFO - Number of results in first chunk: 3 (cursor.py:1166)
2024-11-21 15:15:33,407 - MainThread - snowflake.connector.cursor - INFO - Number of results in first chunk: 1 (cursor.py:1166)
2024-11-21 15:15:33,460 - MainThread - sqlmesh.core.engine_adapter.base - INFO - Executing SQL: SELECT COUNT(*) FROM (SELECT * FROM (SELECT ROW_NUMBER() OVER (PARTITION BY ("ITEM_ID") ORDER BY ("ITEM_ID") NULLS FIRST) AS "RANK_" FROM (SELECT * FROM "SQLMESH_DEMO"."sqlmesh__SQL_MODELS"."SQL_MODELS__VIEW_MODEL__704933569" AS "SQL_MODELS__VIEW_MODEL__704933569") AS "_Q_0" WHERE TRUE) AS "_Q_1" WHERE "RANK_" > 1) AS "audit" (base.py:2062)
2024-11-21 15:15:33,621 - MainThread - snowflake.connector.cursor - INFO - Number of results in first chunk: 1 (cursor.py:1166)
2024-11-21 15:15:33,730 - MainThread - snowflake.connector.cursor - INFO - Number of results in first chunk: 1 (cursor.py:1166)
2024-11-21 15:15:33,733 - MainThread - sqlmesh.core.snapshot.evaluator - WARNING - Audit 'unique_values' for model 'sql_models.view_model' failed.
Got 5 results, expected 0.
SELECT * FROM (SELECT ROW_NUMBER() OVER (PARTITION BY ("ITEM_ID") ORDER BY ("ITEM_ID") NULLS FIRST) AS "RANK_" FROM (SELECT * FROM "SQLMESH_DEMO"."sqlmesh__SQL_MODELS"."SQL_MODELS__VIEW_MODEL__704933569" AS "SQL_MODELS__VIEW_MODEL__704933569") AS "_Q_0" WHERE TRUE) AS "_Q_1" WHERE "RANK_" > 1
Audit is warn only so proceeding with execution. (evaluator.py:890)
2024-11-21 15:15:33,757 - MainThread - sqlmesh.core.snapshot.evaluator - INFO - Auditing snapshot SnapshotId<"SQLMESH_DEMO"."SQL_MODELS"."TESTING_MODEL": 1479244583> (evaluator.py:428)
2024-11-21 15:15:33,759 - MainThread - sqlmesh.core.engine_adapter.base - INFO - Executing SQL: DESCRIBE TABLE "SQLMESH_DEMO"."sqlmesh__SQL_MODELS"."SQL_MODELS__TESTING_MODEL__218764982" (base.py:2062)
2024-11-21 15:15:33,881 - MainThread - snowflake.connector.cursor - INFO - Number of results in first chunk: 2 (cursor.py:1166)
2024-11-21 15:15:33,989 - MainThread - snowflake.connector.cursor - INFO - Number of results in first chunk: 1 (cursor.py:1166)
2024-11-21 15:15:34,016 - MainThread - sqlmesh.core.engine_adapter.base - INFO - Executing SQL: SELECT COUNT(*) FROM (SELECT * FROM (SELECT * FROM "SQLMESH_DEMO"."sqlmesh__SQL_MODELS"."SQL_MODELS__TESTING_MODEL__218764982" AS "SQL_MODELS__TESTING_MODEL__218764982") AS "_Q_0" WHERE "ITEM_ID" < 2) AS "audit" (base.py:2062)
2024-11-21 15:15:34,144 - MainThread - snowflake.connector.cursor - INFO - Number of results in first chunk: 1 (cursor.py:1166)
2024-11-21 15:15:34,254 - MainThread - snowflake.connector.cursor - INFO - Number of results in first chunk: 1 (cursor.py:1166)
2024-11-21 15:15:34,257 - MainThread - sqlmesh.core.snapshot.evaluator - WARNING - Audit 'assert_positive_order_ids' for model 'sql_models.testing_model' failed.
Got 6 results, expected 0.
SELECT * FROM (SELECT * FROM "SQLMESH_DEMO"."sqlmesh__SQL_MODELS"."SQL_MODELS__TESTING_MODEL__218764982" AS "SQL_MODELS__TESTING_MODEL__218764982") AS "_Q_0" WHERE "ITEM_ID" < 2
Audit is warn only so proceeding with execution. (evaluator.py:890)
2024-11-21 15:15:34,331 - MainThread - snowflake.connector.connection - INFO - closed (connection.py:789)
2024-11-21 15:15:34,422 - MainThread - snowflake.connector.connection - INFO - No async queries seem to be running, deleting session (connection.py:795)
2024-11-21 15:15:34,517 - MainThread - snowflake.connector.connection - INFO - closed (connection.py:789)
2024-11-21 15:15:34,611 - MainThread - snowflake.connector.connection - INFO - No async queries seem to be running, deleting session (connection.py:795)
2024-11-21 15:15:34,712 - MainThread - root - INFO - Shutting down the event dispatcher (dispatcher.py:159)
